name: web_project-dev
services:
  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend/Dockerfile.dev
      args:
        USER_ID: ${LOCAL_UID:-1000}
        GROUP_ID: ${LOCAL_GID:-1000}
    ports:
      - "5173:5173"
    env_file:
      - ../../frontend/.env.development
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: http://backend:8080
    volumes:
      - ../../frontend:/workspace
      - frontend-node-modules:/workspace/node_modules
      - frontend-pnpm-store:/home/app/.pnpm-store
    depends_on:
      backend:
        condition: service_started
    networks:
      - web-net

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend/Dockerfile.dev
      args:
        USER_ID: ${LOCAL_UID:-1000}
        GROUP_ID: ${LOCAL_GID:-1000}
    ports:
      - "8080:8080"
    env_file:
      - ../../backend/.env.development
    environment:
      SPRING_OUTPUT_ANSI_ENABLED: "ALWAYS"
    volumes:
      - ../../backend:/workspace
      - gradle-cache:/workspace/.gradle
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web-net

  mysql:
    build:
      context: ../..
      dockerfile: infra/docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
    volumes:
      - mysql-data-dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - web-net

  nginx:
    build:
      context: ../..
      dockerfile: infra/docker/nginx/Dockerfile
    ports:
      - "8081:80"
    env_file:
      - ../nginx/.env.development
    volumes:
      - ../nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ../nginx/proxy-headers.conf:/etc/nginx/snippets/proxy-headers.conf:ro
      - certbot-dev:/var/www/certbot
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - web-net

networks:
  web-net:
    driver: bridge

volumes:
  frontend-node-modules:
  frontend-pnpm-store:
  gradle-cache:
  mysql-data-dev:
  certbot-dev:
