name: deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "모든 서비스에 공통 적용할 태그 (미지정 시 latest)"
        required: false
        default: ""
      fe_tag:
        description: "frontend 이미지 태그 (미지정 시 image_tag 또는 latest)"
        required: false
        default: ""
      be_tag:
        description: "backend 이미지 태그 (미지정 시 image_tag 또는 latest)"
        required: false
        default: ""
      nginx_tag:
        description: "nginx 이미지 태그 (미지정 시 image_tag 또는 latest)"
        required: false
        default: ""
      db_tag:
        description: "mysql 이미지 태그 (미지정 시 image_tag 또는 latest)"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload compose file to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          source: infra/docker/docker-compose.prod.yml
          target: ~/srv/web_project/
          strip_components: 2

      - name: Upload deployment script to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          source: infra/deploy-blue-green.sh
          target: ~/srv/web_project/
          strip_components: 0

      - name: Execute deployment on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_SSH_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          script: |
            set -euo pipefail
            WORKDIR="$HOME/srv/web_project"
            mkdir -p "$WORKDIR" "$WORKDIR/backend" "$WORKDIR/nginx"
            # set server root for compose
            export SERVER_ROOT="$WORKDIR"

            COMMON_TAG="${{ inputs.image_tag }}"

            set_tag() {
              local name="$1"
              local value="$2"
              if [ -n "$value" ]; then
                export "$name"="$value"
              elif [ -n "$COMMON_TAG" ]; then
                export "$name"="$COMMON_TAG"
              fi
            }

            set_tag FE_TAG "${{ inputs.fe_tag }}"
            set_tag BE_TAG "${{ inputs.be_tag }}"
            set_tag NGINX_TAG "${{ inputs.nginx_tag }}"

            if [ -n "${{ inputs.db_tag }}" ]; then
              export DB_TAG="${{ inputs.db_tag }}"
            fi

            cd "$WORKDIR"
            chmod +x infra/deploy-blue-green.sh
            infra/deploy-blue-green.sh
